name: Access github context via JSON

on:
  issue_comment:
    types:
      - created

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT" | jq

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: docker run --rm -v "$(pwd):/src" -w /src ghcr.io/siketyan/automan:latest
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
