name: Access github context via JSON

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT" | jq
