name: Access github context via JSON

on:
  issue_comment:
    types:
      - created

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT" | jq

      - run: docker run --rm ghcr.io/siketyan/automan:latest
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
